# **第04讲 矩阵的基础知识** `课后习题答案`

<font color="blue">作者：欧新宇（Xinyu OU）</font>

<font color="red">本文档所展示的测试结果，均运行于：Intel Core i7-7700K CPU 4.2GHz</font>

---

- ### **作业要求及提交**

1. 将所有运行结果保存为一个`word`文档（特别推荐保存为`pdf`文档进行提交）
2. 要求：使用编程环境完成下列习题，并按题目顺序进行排版，每个题目要求按如下顺序组织（若存在）:  
`0).`题目(将题目完整Copy到作业文档中，可以通过公式编辑器编辑或截图方式）；  
`1).`需要手工书写的部分，请尽量在word文档中进行编辑（迫不得已时，可书写在纸上并拍照）；  
`2).`代码（尽量通过从编程环境截图粘贴）；  
`3).`运行结果贴于文档中。 （复制运行结果到文档或通过截图粘贴）  
`x). ` **如果熟悉本编程环境'Jupyter Notebook'也可以直接在本环境中编写所有文稿及代码，并打印成pdf文档进行提交。**
3. 将文档上传至 `课堂派` 平台

> 注意：截图只需要截取必要部分。此外，请确保截图清晰可见。


-  ### **答案及解析**

**1. 编写Python代码，实现以下矩阵的创建，并显示（打印）到屏幕。**

$(1). A=\begin{bmatrix}
2 & 1 & 4 & 0 \\
1 & -1 & 3 & 4 \\
\end{bmatrix}$

$(2). B=\begin{bmatrix}
1 & 3 & 1 \\
0 & -1 & 2 \\
1 & -3 & 1 \\
4 & 0 & -2 \\
\end{bmatrix}$


解：

In [3]:
import numpy as np
A = np.array([[2,1,4,0],[1,-1,3,4]])
B = np.array([[1,3,1],[0,-1,2],[1,-3,1],[4,0,-2]])

print('A= \n{}'.format(A))
print('B= \n{}'.format(B))

A= 
[[ 2  1  4  0]
 [ 1 -1  3  4]]
B= 
[[ 1  3  1]
 [ 0 -1  2]
 [ 1 -3  1]
 [ 4  0 -2]]


**2. 【计算题】给定以下两个矩阵A和B，试求线性组合S=2.4A+1.7B，并将结果显示（打印）到屏幕。**

$A=\begin{bmatrix}
2.2 & 1.5 & 4.4 \\
1.4 & -1.1 & 3.1 \\
\end{bmatrix}, 
B=\begin{bmatrix}
1.2 & 3 & 1.6 \\
0 & -1.8 & 2.3 \\
\end{bmatrix}$

解：

In [6]:
import numpy as np
A = np.array([[2.2,1.5,4.4],[1.4,-1.1,3.1]])
B = np.array([[1.2,3,1.6],[0,-1.8,2.3]])

S = 2.4 * A + 1.7 * B

print('S = \n{}'.format(S))

S = 
[[ 7.32  8.7  13.28]
 [ 3.36 -5.7  11.35]]
