# 课后作业答案：矩阵

<font color="blue">作者：欧新宇（Xinyu OU）</font>

<font color="red">本文档所展示的测试结果，均运行于：Intel Core i7-7700K CPU 4.2GHz</font>

---

<font style="color:red;font-weight:bold;">以下作业尽量使用Python实现。</font>

**1. 编写Python代码，实现以下矩阵的创建，并显示（打印）到屏幕。**

$(1). A=\begin{bmatrix}
2 & 1 & 4 & 0 \\
1 & -1 & 3 & 4 \\
\end{bmatrix}$

$(2). B=\begin{bmatrix}
1 & 3 & 1 \\
0 & -1 & 2 \\
1 & -3 & 1 \\
4 & 0 & -2 \\
\end{bmatrix}$


解：

In [3]:
import numpy as np
A = np.array([[2,1,4,0],[1,-1,3,4]])
B = np.array([[1,3,1],[0,-1,2],[1,-3,1],[4,0,-2]])

print('A= \n{}'.format(A))
print('B= \n{}'.format(B))

A= 
[[ 2  1  4  0]
 [ 1 -1  3  4]]
B= 
[[ 1  3  1]
 [ 0 -1  2]
 [ 1 -3  1]
 [ 4  0 -2]]


**2. 【计算题】给定以下两个矩阵A和B，试求线性组合S=2.4A+1.7B，并将结果显示（打印）到屏幕。**

$A=\begin{bmatrix}
2.2 & 1.5 & 4.4 \\
1.4 & -1.1 & 3.1 \\
\end{bmatrix}, 
B=\begin{bmatrix}
1.2 & 3 & 1.6 \\
0 & -1.8 & 2.3 \\
\end{bmatrix}$

解：

In [4]:
import numpy as np
A = np.array([[2.2,1.5,4.4],[1.4,-1.1,3.1]])
B = np.array([[1.2,3,1.6],[0,-1.8,2.3]])

S = 2.4 * A + 1.7 * B

print('S = \n{}'.format(S))

S = 
[[ 7.32  8.7  13.28]
 [ 3.36 -5.7  11.35]]


**3. 【计算题】使用Python代码，求解以下矩阵运算**

(1) 求矩阵的乘积：$S = \begin{bmatrix}
2 & 1 & 4 & 0 \\
1 & -1 & 3 & 4 \\
\end{bmatrix}
\begin{bmatrix}
1 & 3 & 1 \\
0 & -1 & 2 \\
1 & -3 & 1 \\
4 & 0 & -2 \\
\end{bmatrix}$

(2) 设$A = \begin{bmatrix}
1 & 2 & 1 & 0 \\
2 & 1 & 0 & 1 \\
3 & -2 & 2 & 1 \\
1 & 2 & 4 & 3 \\
\end{bmatrix}$，
$B = \begin{bmatrix}
3 & 4 & 1 & -2 \\
2 & 1 & 2 & 2 \\
2 & -2 & 2 & 1 \\
1 & 2 & -4 & 3 \\
\end{bmatrix}$，求$M = 4A^2 + 3AB - 2BA+ 5B^2 + (AB)^T$。


- 解(1)

In [87]:
import numpy as np
A = np.array([[2,1,4,0],[1,-1,3,4]])
B = np.array([[1,3,1],[0,-1,2],[1,-3,1],[4,0,-2]])

S = np.dot(A,B)
print("A×B=\n {}".format(S))

A×B=
 [[ 6 -7  8]
 [20 -5 -6]]


- 解(2)

In [1]:
import numpy as np
A = np.array([[1,2,1,0],[2,1,0,1],[3,-2,2,1],[1,2,4,3]])
B = np.array([[3,4,1,-2],[2,1,2,2],[2,-2,2,1],[1,2,-4,3]])

M = 4*np.dot(A,A)+3*np.dot(A,B)-2*np.dot(B,A)+5*np.dot(B,B)+(np.dot(A,B).T)
print("4A^2+3AB-2BA+5B^2+(AB)^T=\n {}".format(M))

4A^2+3AB-2BA+5B^2+(AB)^T=
 [[129  71 154  26]
 [ 97 107   4  35]
 [ 86  52  10 -23]
 [155  85  -3 141]]


**4. 【应用题】冠状病毒感染人员预测**

冠状病毒的感染是非常快速的，某城市有800万人，在1月15日有2000人确诊感染了冠状病毒。假设每天新增确诊病例为未感染人口的0.4%，每天的治愈率为确诊人群的5%。假设在没有找到有效的抑制病例增加手段和防感染疫苗的情况下，2天，10天，20天，50天，100天后分别有多少确诊病例。

**【进阶问题】** <font color="blue">按照当前的设定，多少天以后达到峰值，即：新增确诊病例和新增治愈人数基本一致。</font>

**【扩展问题】** <font color="red">有兴趣的同学可以考虑，如何利用Python获取，当治愈率上升到一定的程度，或感染率降低到一定的程度后，出现拐点的日期。</font>


解：我们可以用如下思路构建传染矩阵X。
1. 矩阵X的第一行第一个元素为一天后仍然没有被感染的人占前一天没有被感染人群的百分比; 第一行第二个元素为前一天被治愈的人群占前一天确诊感染人群的百分比。。
2. 矩阵A的第二行第一个元素为一天后被感染确诊的人占前一天没有被感染人群的百分比；第二行第二个元素为前一天确诊的同时没有被治愈的人占前一天确诊人群的百分比。

则有:
$A=\begin{bmatrix}
99.6/100 & 5/100 \\
0.4/100 & 95/100 \\
\end{bmatrix}$

若令 $x=\begin{bmatrix} 8000000-2000 \\ 2000 \end{bmatrix}$，则1天后确诊感染人数和正常人数可以用$A$乘以$x$计算。其中`(8000000-2000)*(99.6/100)`表示原来正常人群中仍然没有被感染的人数，`2000*(5/100)`表示一天后被治愈的人数，两者相加就是1天后正常人群的总数；`(8000000-2000)*(0.4/100)`表示新增确诊病例，`2000*(95/100)`表示一天后仍然没有被治愈的确诊人数，两者相加就是1天后处于确诊状态的被感染人群。

$Ax=\begin{bmatrix}
99.6/100 & 5/100 \\
0.4/100 & 95/100 \\
\end{bmatrix}
\begin{bmatrix} 
8000000-2000 \\
2000 \\
\end{bmatrix}
=\begin{bmatrix} 
0.996*7998000 + 0.05*2000 \\
0.004*7998000 + 0.95*2000 \\
\end{bmatrix}
=\begin{bmatrix} 
‭7,966,108‬ \\
‭33,892‬ \\
\end{bmatrix}$

一般地说，n天后，感染冠状病毒的人数和正常人数，可由$A^n x$求得。

In [89]:
import numpy as np
A = np.array([[0.996, 0.05],[0.004,0.95]])
x = np.array([[7998000],[2000]])

n = [2, 10, 20, 50, 100] # n=1:A^2; n=2:A^3

person = np.dot(A,x)

for i in n:
    for j in range(i-1):
        person = np.dot(A, person)

    print("{:3d}天后，未感染人数为{:.0f}，确诊人数为{:.0f}".format(i, person[0][0], person[1][0]))


  2天后，未感染人数为7935938，确诊人数为64062
 10天后，未感染人数为7728101，确诊人数为271899
 20天后，未感染人数为7519099，确诊人数为480901
 50天后，未感染人数为7414764，确诊人数为585236
100天后，未感染人数为7407438，确诊人数为592562


**【进阶问题】** <font color="blue">按照当前的设定，多少天以后达到峰值，即：新增确诊病例和新增治愈人数基本一致。</font>
> 基本思路是设置一个`峰值`，当某一天确诊人数不再增长时，即确诊人数不高于峰值人数时，循环停止。

- 方法一：使用for循环

In [90]:
import numpy as np
A = np.array([[0.996, 0.05],[0.004,0.95]])
x = np.array([[7998000],[2000]])

n = 999999 # n=1:A^2; n=2:A^3

person = np.dot(A,x)
top = 0

for i in range(n-1):
    person = np.dot(A, person)
    if top < person[1][0]:
        top = person[1][0]
#         print("\r {:3d}天后，未感染人数为{:.0f}，确诊人数为{:.0f}".format(i, person[0][0], person[1][0]), end="")
    else:
        print("\n 峰值出现在第{:3d}天，此时未感染人数为{:.0f}，确诊人数为{:.0f}".format(i, person[0][0], person[1][0]))
        break


 峰值出现在第612天，此时未感染人数为7407407，确诊人数为592593


- 方法二：使用while循环

In [91]:
import numpy as np
A = np.array([[0.996, 0.05],[0.004,0.95]])
x = np.array([[7998000],[2000]])

person = np.dot(A,x)
top = person[1][0]
person = np.dot(A, person)
i = 0

while top < person[1][0]:    
    top = person[1][0]
    person = np.dot(A, person)
    i = i + 1

print("\n 峰值出现在第{:3d}天，此时未感染人数为{:.0f}，确诊人数为{:.0f}".format(i, person[0][0], person[1][0]))



 峰值出现在第612天，此时未感染人数为7407407，确诊人数为592593
